/**
 * Branded types for session IDs to prevent confusion between different types of sessions.
 *
 * These types use TypeScript's branded type pattern to create distinct types that are
 * incompatible with each other at compile time, preventing accidental misuse.
 */

/**
 * Authentication session ID - identifies a user's authentication session.
 * Generated by: Frontend client (webapp)
 * Used for: User authentication and authorization
 */
export type AuthSessionId = string & { readonly __brand: 'AuthSessionId' };

/**
 * Chat session ID - identifies a chat conversation in Convex.
 * Generated by: Backend (Convex) when startSession is called
 * Used for: Database operations, frontend routing, URL state
 */
export type ChatSessionId = string & { readonly __brand: 'ChatSessionId' };

/**
 * OpenCode session ID - identifies a session in the OpenCode AI system.
 * Generated by: OpenCode SDK in worker process
 * Used for: Sending prompts to OpenCode AI model
 */
export type OpencodeSessionId = string & { readonly __brand: 'OpencodeSessionId' };

/**
 * Type guard to check if a value is a valid session ID string.
 */
export function isValidSessionId(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0;
}

/**
 * Safely cast a string to ChatSessionId after validation.
 * Use this when receiving session IDs from external sources (API, database, etc.)
 */
export function toChatSessionId(value: string): ChatSessionId {
  if (!isValidSessionId(value)) {
    throw new Error(`Invalid chat session ID: ${value}`);
  }
  return value as ChatSessionId;
}

/**
 * Safely cast a string to OpencodeSessionId after validation.
 * Use this when receiving session IDs from OpenCode SDK.
 */
export function toOpencodeSessionId(value: string): OpencodeSessionId {
  if (!isValidSessionId(value)) {
    throw new Error(`Invalid opencode session ID: ${value}`);
  }
  return value as OpencodeSessionId;
}

/**
 * Safely cast a string to AuthSessionId after validation.
 * Use this when receiving session IDs from authentication system.
 */
export function toAuthSessionId(value: string): AuthSessionId {
  if (!isValidSessionId(value)) {
    throw new Error(`Invalid auth session ID: ${value}`);
  }
  return value as AuthSessionId;
}
